import ClientLayout from "@/Components/ClientLayout";
import "./globals.css";



export const metadata = {
  title: "Sayan Lifestyle",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
