import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/NavBar";
import { ToastContainer } from "react-toastify";

import Footer from "@/Components/Footer";
import ClientProvider from "@/Components/ClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sayan Lifestyle",
  description: "Generated by create next app",
};

export default function RootLayout({ 
  children }) {
  return (
    <html lang="en">
  
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ToastContainer />
          <Navbar />
          <ClientProvider>
          {children}</ClientProvider>
          <Footer></Footer>
        </body>

    </html>
  );
}
