import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/NavBar";
import { ToastContainer } from "react-toastify";
import NextSessionProvider from "@/Providers/NextSessionProvider/NextSessionProvider";
import Footer from "@/Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sayan Lifestyle",
  description: "Generated by create next app",
};

export default function RootLayout({ 
  children }) {
  return (
    <html lang="en">
      <NextSessionProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ToastContainer />
          <Navbar />
          {children}
          <Footer></Footer>
        </body>
      </NextSessionProvider>
    </html>
  );
}
